### ISSUE TITLE
Walkback post install and save image a couple of times

### ISSUE THREAD

**Issue by sanjayminni** [fxgallego/DolphinHttpServer#15]
I  start getting this walkback anytime shortly after installing seaside which includes DolphinHttpServer. 
I tried several times in all combinations with a clean image

Here is a way i reproduced it (D7.1.20 Windows 10)
- started with a clean image
- loaded seaside thru package browser
- moved around in welcome screen played with counter
- saved image in dolphin (welcome screen still open) (*see note 1 below)
- then closed the welcome screen but other tabs in browser open not related to seaside
- saved image again
- exited
- restarted dolphin and ... error message appeared

however saving image with a seaside web screen still open is not the only way - i keep getting it in various ways to the point if D7+Seaside being impossible to use. 
Once it appears the walkback appears on D7 start, File-Save Image but does not come when you do a File->Exit Dolphin [save image->yes].

![DolphinSeasideErr](https://user-images.githubusercontent.com/12030766/115209948-bbb01480-a11b-11eb-870b-0a2062770e8d.jpg)

[DPROerrors.txt](https://github.com/fxgallego/DolphinHttpServer/files/6334659/DPROerrors.txt)

![DolphinSeasideErr](https://user-images.githubusercontent.com/12030766/115210513-4c86f000-a11c-11eb-83d7-a2064e97fcac.jpg)

**Comment by fxgallego** [comment]
Could you confirm that this does not happens if you never save the image?

**Comment by sanjayminni** [comment]
Seems the issue does not happen if i do not save the image

I loaded a fresh image and loaded rko281/seaside followed by
rko281/seaside-bootstrap4
and closed all tabs and saved the image (just this once)

thereafter restarted opened all tabs from links in seaside welcome screen,
bootstrap played around closed dolphin without saving image and repeated
this sequence - problem did not happen

and then once while exiting I saved the image on next startup the problem
surfaced

**Comment by sanjayminni** [comment]
also observed
on a fresh image only installed DolphinHttpServer\Dolhin Http Server Demo.pax
repeated the sequence sequence several times:

1. start image
     in a workspace:
     1.1 - HttpServerDemo start.
                                   <-- problem only if i save image / exit dolphin here*
     1.2 - HttpServerDemo stop.
2. save image / exit Dolphin

*Problem surfaces on restart of image or even start/stop of HttpServerDemo. but then after that after a successful stop and save the problem seems to go away

**Comment by fxgallego** [comment]
Seems to me it's an inoffensive issue because if you close the walkback screen the server still runs. In my machine I can't reproduce always, seems to be a race condition issue because I'm receiving an invalid request. I believe we can safely ignore it if it does not produce any other side effects. I mean, it's only a development issue, I think.

**Comment by sanjayminni** [comment]
In my machine it starts occurring immediately and regularly even though
each time i start with a fresh image (in development).

Then every time I save / exit or re-start the image, (which will be
frequent during development), at least 3-4 walkback window comes and these
have to be terminated to move further.

So far I have not progress beyond the seaside & seaside-bootstrap demo as I
am not sure of impact.

is there any way to get a handle and shut down the server before saving and
to restart the same. Maybe at least this walkback occurrence can be
controlled.

with warm regards
Sanjay Minni

**Comment by fxgallego** [comment]
I see, I think something could be done, I will investigate it more deeply.

**Comment by sanjayminni** [comment]
Nope, its still there,

1. installed a new image,
2. Installed rko281/Seaside; Closed the browser tab with seaside welcome screen.
3. Saved image thru Shell->File->Save Image (so did not exit the image - which is still running)
4. Installed rko281/Seaside-Bootstrap4;  Closed the browser tab with bootstrap4 welcome screen.
5. Saved image thru Shell->File->Save Image (so did not exit the image - which is still running)
Walkback appears !

[DPROerrors.txt](https://github.com/fxgallego/DolphinHttpServer/files/6362734/DPROerrors.txt)

![D7HttpServerErr](https://user-images.githubusercontent.com/12030766/115818947-7fcac700-a41b-11eb-8d6b-271cbd25da52.jpg)

**Comment by fxgallego** [comment]
I'm sorry. I can't reproduce this, even loading Seaside in a new image.
Please, could you check if the DolphinHttpServer package is the right one?
The source of `HttpServer>>onSessionStarted` should look like this:
```smalltalk
onSessionStarted
	[self startIfPaused] postToInputQueue
```

**Comment by sanjayminni** [comment]
I am running directly on a Windows 10 i5 8gb machine. are you on something similar ?

However I could not reproduce with only a single package DolphinHttpServer - demo loaded, but am checking it out now

Checked the code as mentioned - it is the latest version only:

onSessionStarted
	[self startIfPaused] postToInputQueue

onImageSaveStarting
	self isRunning
		ifTrue: 
			[state := #paused.
			self stopListenersAndCloseSession.
			(Delay forSeconds: 1) wait	"Wait for other processes to be cleaned before image save."]

**Comment by fxgallego** [comment]
Ok, yes I'm on a i5 also. Please, could you save the image with the process explorer open and upload a screen capture of the process list after the save image?

**Comment by sanjayminni** [comment]
I have shared screen shots with this mail and also the image at
https://drive.google.com/drive/u/0/folders/1hAvpkBGFxsHH27plP4VCGZoJAg1IIl2r

here is a definite way to reproduce the issue
1. install a new image
2. Load GitHub and
3. GitHub rko281/seaside-bootstrap4
4. Close the bootstrap4 welcome page (to be sure)
5. in Dolphin Control Panel do File->Save Image twice (second time walkback
appears)

**Comment by sanjayminni** [comment]
I have shared the image on google drive at for fxgallego@gmail.com
https://drive.google.com/drive/u/0/folders/1hAvpkBGFxsHH27plP4VCGZoJAg1IIl2r

here is a definite way to reproduce the issue
1. install a new image
2. Load GitHub and
3. GitHub rko281/seaside-bootstrap4
4. Close the bootstrap4 welcome page (to be sure)
5. in Dolphin Control Panel do File->Save Image twice (second time walkback
appears)

![d7-01-HttpServerSeasideBootstrapInstalled](https://user-images.githubusercontent.com/12030766/115989461-1d6cf480-a5dc-11eb-898f-6a7c869ddb53.jpg)

![d7-02-HttpServerSeasideBootstrapInstalled-error](https://user-images.githubusercontent.com/12030766/115989473-2d84d400-a5dc-11eb-8d69-ca9bfeec61f7.jpg)

**Comment by sanjayminni** [comment]
pls see a related response at 
https://github.com/rko281/Seaside/issues/6

**Comment by fxgallego** [comment]
Thanks, I'll take a look at this later this week If i have time.

**Comment by fxgallego** [comment]
Ok I implemented and tested the solution provided by John in rko281/Seaside#6
Seems to work ok in my machine.
